### ISSUE TITLE
Reset Timer Without Refreshing Page

### ISSUE THREAD

**Issue by AndrewDant** [cathydeng/are-men-talking-too-much#20]
Currently I don't see any way to reset the timer without refreshing the page. It's not too important but it would be a nice and fairly simple addition.

**Comment by cathydeng** [comment]
this may be nice and simple from a technical implementation standpoint, but not from a design standpoint. i can't think of an elegant way to do this without adding another button, and that would add significant visual clutter. imo the additional functionality isn't worth the cost to clarity.
